# Generated by Django 2.1.3 on 2018-11-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tilte',
            new_name='title',
        ),
    ]
